use std::{sync::Arc, time::Duration};

use crossbeam_skiplist::SkipMap;
use deadpool::{
    Runtime,
    managed::{Manager, Pool, RecycleError},
};

use crate::{container::Container, error::SandboxPoolError, profile::SandboxProfile};

pub type SandboxContainerPool = Pool<SandboxContainerManager>;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SandboxContainerPoolConfig {
    pub max_size: usize,
    pub wait_timeout: Option<Duration>,
    pub create_timeout: Option<Duration>,
    pub recycle_timeout: Option<Duration>,
}

impl Default for SandboxContainerPoolConfig {
    fn default() -> Self {
        Self {
            max_size: 16,
            wait_timeout: None,
            create_timeout: None,
            recycle_timeout: None,
        }
    }
}

#[derive(Debug, Clone)]
pub struct SandboxContainerManager {
    profile: SandboxProfile,
}

impl SandboxContainerManager {
    pub fn new(profile: SandboxProfile) -> Self {
        Self { profile }
    }

    pub fn profile(&self) -> &SandboxProfile {
        &self.profile
    }

    pub fn into_pool(
        self,
        config: SandboxContainerPoolConfig,
    ) -> Result<SandboxContainerPool, SandboxPoolError> {
        Pool::builder(self)
            .max_size(config.max_size)
            .runtime(Runtime::Tokio1)
            .wait_timeout(config.wait_timeout)
            .create_timeout(config.create_timeout)
            .recycle_timeout(config.recycle_timeout)
            .build()
            .map_err(|source| SandboxPoolError::BuildPool { source })
    }
}

impl Manager for SandboxContainerManager {
    type Type = Container;

    type Error = SandboxPoolError;

    async fn create(&self) -> Result<Self::Type, Self::Error> {
        Ok(Container::new(self.profile.clone()))
    }

    async fn recycle(
        &self,
        obj: &mut Self::Type,
        _metrics: &deadpool::managed::Metrics,
    ) -> deadpool::managed::RecycleResult<Self::Error> {
        if obj.is_healthy() {
            Ok(())
        } else {
            Err(RecycleError::message("sandbox container is unhealthy"))
        }
    }
}

#[derive(Debug, Clone)]
pub struct SandboxPoolRegistry {
    config: SandboxContainerPoolConfig,
    inner: Arc<SkipMap<SandboxProfile, SandboxContainerPool>>,
}

impl SandboxPoolRegistry {
    pub fn new() -> Self {
        Self::with_config(SandboxContainerPoolConfig::default())
    }

    pub fn with_config(config: SandboxContainerPoolConfig) -> Self {
        Self {
            config,
            inner: Arc::new(SkipMap::new()),
        }
    }

    pub fn get_or_create_pool(
        &self,
        profile: SandboxProfile,
    ) -> Result<SandboxContainerPool, SandboxPoolError> {
        if let Some(pool) = self.inner.get(&profile) {
            return Ok(pool.value().clone());
        }

        let pool = SandboxContainerManager::new(profile.clone()).into_pool(self.config)?;

        if let Some(existing_pool) = self.inner.get(&profile) {
            return Ok(existing_pool.value().clone());
        }

        self.inner.insert(profile.clone(), pool.clone());
        if let Some(inserted_pool) = self.inner.get(&profile) {
            Ok(inserted_pool.value().clone())
        } else {
            Ok(pool)
        }
    }

    pub fn pool_count(&self) -> Result<usize, SandboxPoolError> {
        Ok(self.inner.len())
    }
}

impl Default for SandboxPoolRegistry {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use bytesize::ByteSize;

    use super::*;
    use crate::profile::ResourceLimits;

    fn profile(image: &str, memory_mib: u64, cpu_percent: u8) -> SandboxProfile {
        SandboxProfile::new(
            image,
            ResourceLimits::new(ByteSize::mib(memory_mib), cpu_percent)
                .expect("resource limits should build"),
        )
        .expect("profile should build")
    }

    #[test]
    // NOTE: THIS UNIT TEST GENERATED BY LLM
    fn reuses_pool_for_same_profile() {
        let pools = SandboxPoolRegistry::with_config(SandboxContainerPoolConfig::default());
        let sandbox_profile = profile("docker.io/library/alpine:3.21", 256, 80);

        let first = pools
            .get_or_create_pool(sandbox_profile.clone())
            .expect("pool should be created");
        let second = pools
            .get_or_create_pool(sandbox_profile)
            .expect("pool should be reused");

        assert_eq!(
            pools.pool_count().expect("pool count should be readable"),
            1
        );
        assert_eq!(first.manager().profile(), second.manager().profile());
    }

    #[test]
    // NOTE: THIS UNIT TEST GENERATED BY LLM
    fn creates_distinct_pools_for_distinct_profiles() {
        let pools = SandboxPoolRegistry::with_config(SandboxContainerPoolConfig::default());
        let profile_a = profile("docker.io/library/alpine:3.21", 256, 80);
        let profile_b = profile("docker.io/library/alpine:3.21", 512, 50);

        let first = pools
            .get_or_create_pool(profile_a)
            .expect("first pool should be created");
        let second = pools
            .get_or_create_pool(profile_b)
            .expect("second pool should be created");

        assert_eq!(
            pools.pool_count().expect("pool count should be readable"),
            2
        );
        assert_ne!(first.manager().profile(), second.manager().profile());
    }

    #[test]
    // NOTE: THIS UNIT TEST GENERATED BY LLM
    fn concurrent_get_or_create_pool_keeps_single_pool_for_same_profile() {
        let pools = Arc::new(SandboxPoolRegistry::with_config(
            SandboxContainerPoolConfig::default(),
        ));
        let sandbox_profile = profile("docker.io/library/alpine:3.21", 256, 80);

        let mut handles = Vec::new();
        for _ in 0..8 {
            let pools = Arc::clone(&pools);
            let sandbox_profile = sandbox_profile.clone();
            handles.push(std::thread::spawn(move || {
                pools
                    .get_or_create_pool(sandbox_profile)
                    .expect("pool should be created or reused")
            }));
        }

        let mut returned_pools = Vec::new();
        for handle in handles {
            returned_pools.push(handle.join().expect("thread should finish"));
        }

        assert_eq!(
            pools.pool_count().expect("pool count should be readable"),
            1
        );

        for pool in returned_pools {
            assert_eq!(pool.manager().profile(), &sandbox_profile);
        }
    }
}
