use crate::error::SandboxProfileError;
use bollard::models::HostConfig;
use bytesize::ByteSize;

/// Keep a fixed CFS period so "cpu utilization percent" can be converted into a stable quota.
const CPU_PERIOD_MICROS: i64 = 100_000;

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct SandboxProfile {
    pub image: String,
    pub resources: ResourceLimits,
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ResourceLimits {
    memory: ByteSize,
    cpu_period: i64,
    cpu_quota: i64,
}

impl SandboxProfile {
    pub fn new(
        image: impl Into<String>,
        resources: ResourceLimits,
    ) -> Result<Self, SandboxProfileError> {
        let profile = Self {
            image: image.into(),
            resources,
        };
        Ok(profile)
    }

    pub fn to_host_config(&self) -> Result<HostConfig, SandboxProfileError> {
        let memory = i64::try_from(self.resources.memory.0).map_err(|_| {
            SandboxProfileError::MemoryTooLarge {
                memory_bytes: self.resources.memory.0,
            }
        })?;

        Ok(HostConfig {
            memory: Some(memory),
            cpu_period: Some(self.resources.cpu_period),
            cpu_quota: Some(self.resources.cpu_quota),
            ..Default::default()
        })
    }
}

impl ResourceLimits {
    pub fn new(memory: ByteSize, cpu_utilization_percent: u8) -> Result<Self, SandboxProfileError> {
        let limits = Self {
            memory,
            cpu_period: CPU_PERIOD_MICROS,
            cpu_quota: cpu_quota_from_percent(cpu_utilization_percent),
        };
        Ok(limits)
    }
}

fn cpu_quota_from_percent(cpu_utilization_percent: u8) -> i64 {
    (CPU_PERIOD_MICROS * i64::from(cpu_utilization_percent)) / 100
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    // NOTE: THIS UNIT TEST GENERATED BY LLM
    fn maps_cpu_and_memory_into_host_config() {
        let cases = [
            (50_u8, 50_000_i64),
            (80_u8, 80_000_i64),
            (100_u8, 100_000_i64),
        ];
        for (percent, expected_quota) in cases {
            let profile = SandboxProfile::new(
                "docker.io/library/alpine:3.21",
                ResourceLimits::new(ByteSize::mib(256), percent)
                    .expect("resource limits should build"),
            )
            .expect("profile should be valid");

            let host_config = profile
                .to_host_config()
                .expect("host config mapping should succeed");
            assert_eq!(host_config.memory, Some(256 * 1024 * 1024));
            assert_eq!(host_config.cpu_period, Some(100_000));
            assert_eq!(host_config.cpu_quota, Some(expected_quota));
        }
    }
}
