//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::ActionEnum;
use super::sea_orm_active_enums::ActorEnum;
use super::sea_orm_active_enums::DecisionEnum;
use super::sea_orm_active_enums::ReasonCodeEnum;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "audit_events")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub event_id: Uuid,
    pub task_id: Uuid,
    pub step_id: Uuid,
    pub actor: ActorEnum,
    pub action: ActionEnum,
    pub decision: DecisionEnum,
    pub timestamp: DateTimeWithTimeZone,
    pub reason_code: Option<ReasonCodeEnum>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
