//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::audit_events::Entity as AuditEvents;
pub use super::histories::Entity as Histories;
pub use super::sessions::Entity as Sessions;
