//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "action_enum")]
pub enum ActionEnum {
    #[sea_orm(string_value = "submit_tool_call")]
    SubmitToolCall,
    #[sea_orm(string_value = "evaluate_policy")]
    EvaluatePolicy,
    #[sea_orm(string_value = "execute_tool")]
    ExecuteTool,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "actor_enum")]
pub enum ActorEnum {
    #[sea_orm(string_value = "user")]
    User,
    #[sea_orm(string_value = "agent")]
    Agent,
    #[sea_orm(string_value = "system")]
    System,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "decision_enum")]
pub enum DecisionEnum {
    #[sea_orm(string_value = "allow")]
    Allow,
    #[sea_orm(string_value = "deny")]
    Deny,
    #[sea_orm(string_value = "escalate")]
    Escalate,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "history_role")]
pub enum HistoryRole {
    #[sea_orm(string_value = "user")]
    User,
    #[sea_orm(string_value = "assistant")]
    Assistant,
    #[sea_orm(string_value = "system")]
    System,
    #[sea_orm(string_value = "tool")]
    Tool,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "reason_code_enum")]
pub enum ReasonCodeEnum {
    #[sea_orm(string_value = "policy_denied")]
    PolicyDenied,
    #[sea_orm(string_value = "policy_input_invalid")]
    PolicyInputInvalid,
    #[sea_orm(string_value = "sandbox_timeout")]
    SandboxTimeout,
    #[sea_orm(string_value = "sandbox_resource_exceeded")]
    SandboxResourceExceeded,
    #[sea_orm(string_value = "sandbox_fs_violation")]
    SandboxFsViolation,
    #[sea_orm(string_value = "sandbox_network_violation")]
    SandboxNetworkViolation,
    #[sea_orm(string_value = "runtime_internal_error")]
    RuntimeInternalError,
    #[sea_orm(string_value = "unknown_fallback")]
    UnknownFallback,
}
